spring:
  application:
    name: product-service
  datasource:
    url: ${PRODUCT_DB_URL}
    username: ${PRODUCT_DB_USERNAME}
    password: ${PRODUCT_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoint:
    web:
      exposure:
        include: health,info
server:
  port: 8082
